// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WailsDbCreateBookmark(arg1) {
  return window['go']['main']['App']['WailsDbCreateBookmark'](arg1);
}

export function WailsDbDeleteBookmark(arg1, arg2) {
  return window['go']['main']['App']['WailsDbDeleteBookmark'](arg1, arg2);
}

export function WailsDbGetAllBookmarks() {
  return window['go']['main']['App']['WailsDbGetAllBookmarks']();
}

export function WailsDbGetBookmark(arg1) {
  return window['go']['main']['App']['WailsDbGetBookmark'](arg1);
}

export function WailsDbUpdateBookmark(arg1) {
  return window['go']['main']['App']['WailsDbUpdateBookmark'](arg1);
}
