// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function WailsDbCreateBookmark(arg1:main.Bookmarks):Promise<main.Bookmarks>;

export function WailsDbDeleteBookmark(arg1:number,arg2:boolean):Promise<main.Bookmarks>;

export function WailsDbGetAllBookmarks():Promise<Array<main.Bookmarks>>;

export function WailsDbGetBookmark(arg1:main.Bookmarks):Promise<Array<main.Bookmarks>>;

export function WailsDbUpdateBookmark(arg1:main.Bookmarks):Promise<main.Bookmarks>;
